name: Using another time-zone

on: [push]

jobs:
  Change-Time-Zone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Show free memory
        run: free -h
      - name: Show disk usage
        run: |
          pwd
          sudo df -ah
      - name: Show fdisk
        run: sudo fdisk -l
      - name: Test Docker (sudo)
        run: |
          sudo docker --version
          sudo docker run --rm hello-world
      - name: Test Docker (regular user)
        run: |
          docker --version
          docker run --rm hello-world
      # - name: Install Emacs
      #   run: |
      #     sudo snap install emacs --classic
      #     emacs --version | head -n1
      - run: sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - run: date
      # - run: emacs -Q --batch --eval '(print (current-time-zone))'
      # - run: emacs -Q --batch --eval '(print (current-time-string))'
