name: Using another time-zone

on: [push]

jobs:
  Change-Time-Zone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Show disk usage
        run: |
          sudo df -h
      - name: Install Emacs
        run: |
          sudo snap install emacs --classic
          emacs --version | head -n1
      - run: sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - run: date
      - run: emacs -Q --batch --eval '(print (current-time-zone))'
      - run: emacs -Q --batch --eval '(print (current-time-string))'
